version: '3.7'

services:
  web:
    container_name: web-container
    build:
      context: ./web
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./web/conf:/etc/nginx/conf.d 
      - ./web/logs/nginx/:/var/log/nginx/
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    networks:
      - django_net
    depends_on:
      - back

  back:
    container_name: back-container
    build:
      context: ./back
      dockerfile: ./Dockerfile
    command: 'sh /usr/src/app/scripts/start.sh'
    restart: always
    volumes:
      - ./back:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8001"
    networks:
      - django_net

  front:
    container_name: front-container
    build:
      context: ./front
      dockerfile: ./Dockerfile  # ./front/Dockerfileを参照
    ports:
      - 8080:8080
    expose:
      - "3000"
    command: 'sh /code/scripts/start.sh'
    volumes:
      - ./front:/code
      - ./front:/app/:cached
      - ./front/node_modules:/app/node_modules
    networks:
      - django_net
    depends_on:
      - back

networks:
  django_net:
    driver: bridge

volumes:
  django_statics:
    driver: local
  static_volume:
  media_volume: